# Generated by Django 2.1.5 on 2019-02-07 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
