# Generated by Django 2.1.5 on 2019-02-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
